apiVersion: v1
kind: ConfigMap
metadata:
  name: przepisnik-cmap
  labels:
    app: przepisnik-deploy
data:
  PORT: "8080"
  DB_URL: "jdbc:postgresql://db-svc.labproj22.svc.cluster.local:5432/przepisnik"
  LISTA_URL: "http://lista-svc.labproj22.svc.cluster.local:8080/"
  OPIS_URL: "http://opis-svc.labproj22.svc.cluster.local:8080/"