apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: lista-deploy
  name: lista
spec:
  host: ""
  port:
    targetPort: 8080
  to:
    kind: Service
    name: lista-svc
    weight: 100