apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: db-deploy
  name: db-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deploy
  template:
    metadata:
      labels:
        app: db-deploy
    spec:
      containers:
      - name: db-deploy
        image: image-registry.openshift-image-registry.svc:5000/labproj22/postgres:14.1
        imagePullPolicy: "IfNotPresent"
        ports:
        - containerPort: 5432
        envFrom:
        - configMapRef:
            name: db-cmap
        env:
        - name: USER_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: USER_DB
        - name: PASSWORD_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: PASSWORD_DB
        volumeMounts:
        - mountPath: /
          name: postgredb
        resources: {}
    volumes:
    - name: postgredb
      persistentVolumeClaim:
        claimName: db-pvc
status: {}