apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: opis-deploy
  name: opis
spec:
  host: ""
  port:
    targetPort: 8080
  to:
    kind: Service
    name: opis-svc
    weight: 100