apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: front-deploy
  name: front-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front-deploy
  template:
    metadata:
      labels:
        app: front-deploy
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/labproj22/frontend:3.3
        name: front-deploy
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: front-cmap
status: {}
