apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app: front-deploy
  name: przepisnik
spec:
  host: ""
  port:
    targetPort: 80
  to:
    kind: Service
    name: front-svc
    weight: 100
