kind: PersistentVolume
apiVersion: v1
metadata:
  name: db-pv
  labels:
    type: local
    app: db-deploy
spec:
  storageClassName: managed-nfs-storage
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/"
