kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: db-pvc
spec:
  storageClassName: managed-nfs-storage
  accessModes:
  - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi