apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: projekt-bb
  name: projekt-bb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: busybox
    spec:
      containers:
      - command:
        - sleep
        - "9000"
        image: image-registry.openshift-image-registry.svc:5000/default/busybox:latest
        name: busybox
        resources: {}
status: {}